version: "3.9"

services:
  postgres:
    image: postgres:10.17
    restart: always
    environment:
      POSTGRES_USER: ${PostgresUser}
      POSTGRES_PASSWORD: ${PostgresPassword}
      POSTGRES_DB: ${PostgresDb}
    ports:
      - "${postgresPort}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  gerdisc:
    build: .
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  db_data:
