name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  POSTGRES_USER: postgress
  POSTGRES_PASSWORD: password
  POSTGRES_DB: gerdisc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker Compose services
      run: |
        cd ../gerdisc
        ls
        docker-compose build
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username radhanama --password-stdin
        docker-compose push
