name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  postgresPort: 5434
  PostgresServer: postgres
  PostgresUser: postgres
  PostgresPassword: ${{ secrets.PostgresPassword }}
  PostgresDb: gerdisc
  SingInKey: ${{ secrets.SingInKey }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build and push Docker Compose services
      run: |
        cd gerdisc
        docker-compose build
        echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username radhanama --password-stdin
        docker-compose push
